name: 'Version Filer'
description: 'Agnostic way of writing a string to a file'
author: 'Simon Blomsterlund'
inputs:
  prepend: 
    required: false
    description: 'string that goes before the value'
    default: '__version__='
  
  value:
    required: true
    description: 'the actual value'
  
  append: 
    required: false
    description: 'string that goes after the value'
    default: ''

  filename:
    required: false
    description: 'Name of the file'
    default: '__version__.py'
  
  filelocation:
    required: false
    description: 'File location relative to root, leave empty for root'
    default: ''
  
  one_line_comment_sign:
    required: false
    description: 'Sign that goes before a single line comment in your programming language'
    default: '#'
runs:
  using: 'node16'
  main: 'lib/index.js'